[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32F446RETx'
rustflags = [
    "-C", "link-arg=-Tlink.x",
#    "-C", "link-arg=-Tdefmt.x",
    "-g",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
